insert into ACCOMODATIONS (name, country, city, address, price) values ('Perameles macao', 'Netherlands', 'Tilburg', '75709 Ohio Park', 757.34);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Lepus fulicarius', 'France', 'Saint-Leu-la-Forêt', '8714 Derek Center', 480.34);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Zosterops indica', 'France', 'Ajaccio', '0848 Manufacturers Trail', 937.76);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Microcebus murinus', 'Germany', 'Bremen', '832 Packers Hill', 416.99);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Alopochen aegyptiacus', 'Netherlands', 'Amsterdam Oud Zuid en Rivierenbuurt', '729 Jenifer Crossing', 855.01);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Lycaon pictus', 'France', 'Hyères', '8 Duke Circle', 414.87);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Phalaropus fulicarius', 'France', 'Brie-Comte-Robert', '55525 Kingsford Avenue', 968.6);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Ratufa indica', 'Netherlands', 'Emmeloord', '009 Golf Plaza', 365.94);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Chauna torquata', 'France', 'Laon', '55290 Golf View Pass', 479.09);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Salvadora hexalepis', 'France', 'Orange', '99788 Dorton Junction', 596.69);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Anser anser', 'France', 'Clermont-Ferrand', '69471 Norway Maple Trail', 687.51);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Spheniscus mendiculus', 'Germany', 'München', '499 Starling Alley', 665.02);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Corvus albicollis', 'United Kingdom', 'Charlton', '02312 Monterey Circle', 429.16);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Ara macao', 'France', 'Creil', '47 Scofield Alley', 112.82);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Rhea americana', 'Italy', 'Reggio Calabria', '18394 Donald Road', 438.65);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Bubalornis niger', 'Italy', 'Milano', '917 Waubesa Court', 788.77);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Anastomus oscitans', 'Netherlands', 'Vlissingen', '96024 Lotheville Place', 612.17);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Anas platyrhynchos', 'Germany', 'Frankfurt am Main', '75838 Dottie Lane', 812.73);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Geochelone elephantopus', 'France', 'Rueil-Malmaison', '700 Vernon Parkway', 946.13);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Tenrec ecaudatus', 'France', 'Paris 17', '86 Forest Alley', 671.22);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Dasypus septemcincus', 'France', 'Évreux', '2577 Service Lane', 314.98);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Varanus salvator', 'France', 'Lille', '44414 Cambridge Place', 386.89);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Caiman crocodilus', 'Netherlands', 'Utrecht (stad)', '323 Hazelcrest Point', 405.17);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Vulpes cinereoargenteus', 'France', 'Saint-Pierre-des-Corps', '3 Bartillon Parkway', 584.51);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Diceros bicornis', 'France', 'Tarbes', '86 Algoma Alley', 525.43);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Leï Suves', 'France', 'Eaton', '52 Kedzie Street', 523.57);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Phacochoerus aethiopus', 'Germany', 'Nürnberg', '23333 Brentwood Pass', 188.77);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Naja haje', 'Germany', 'Frankfurt am Main', '80 Rockefeller Hill', 121.26);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Ovibos moschatus', 'France', 'Les Clayes-sous-Bois', '39 Morrow Road', 972.17);
insert into ACCOMODATIONS (name, country, city, address, price) values ('Macropus robustus', 'France', 'Brest', '486 Fallview Avenue', 499.27);
