insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Chlamydosaurus kingii', 'Greece', 'Loutrós', '5 7th Court', 353, 'Baoshan Yunduan Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Diomedea irrorata', 'Greece', 'Thessaloníki', '227 Grim Street', 685, 'Sendai Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Haliaeetus leucoryphus', 'France', 'Marne-la-Vallée', '047 Longview Way', 104, 'Angoche Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Nyctereutes procyonoides', 'France', 'Lyon', '9 Service Plaza', 295, 'José Celestino Mutis Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Bubalornis niger', 'France', 'La Valette-du-Var', '451 Truax Parkway', 333, 'E. T. Joshua Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Papio cynocephalus', 'France', 'Montreuil', '81 Muir Avenue', 624, 'Dade Collier Training and Transition Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Milvago chimachima', 'Netherlands', 'Enschede', '23940 Stone Corner Park', 664, 'Southport Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Cathartes aura', 'Greece', 'Kokkónion', '77076 Westridge Pass', 909, 'En Nahud Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Felis silvestris lybica', 'Greece', 'Mitrópoli', '8667 Ludington Avenue', 301, 'Bundi Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Bettongia penicillata', 'France', 'Saint-Maixent-l''École', '66 Linden Drive', 469, 'Dangriga Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Pycnonotus barbatus', 'France', 'Angers', '64078 American Terrace', 764, 'Maripasoula Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Haematopus barbatus', 'France', 'Le Cannet', '426 Sycamore Trail', 708, 'Walcha Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Haematopus ater', 'Greece', 'Káto Miliá', '15759 Logan Circle', 210, 'John Wayne Airport-Orange County Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Lamprotornis nitens', 'Greece', 'Loutrá', '00 Kim Plaza', 867, 'Vichadero Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Sula brachyrhynchos', 'France', 'Châlons-en-Champagne', '3996 Boyd Alley', 103, 'Kunsan Air Base');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Corvus brachyrhynchos', 'Germany', 'Dillenburg', '9 Bobwhite Avenue', 786, 'Bengbu Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Naja chalybaeus', 'Greece', 'Sámi', '6 Acker Road', 517, 'Bemichi Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Sula dactylatra', 'Spain', 'Pontevedra', '23 Pine View Crossing', 515, 'Langebaanweg Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Varanus albigularis', 'Netherlands', 'Maastricht', '55 Kensington Plaza', 789, 'Middletown Regional Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Lamprotornis chalybaeus', 'France', 'Meylan', '8 Longview Park', 202, 'Dabra Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Streptopelia senegalensis', 'France', 'Ajaccio', '1 Coolidge Park', 640, 'Ambler Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Coluber constrictor', 'France', 'Annecy', '96 Brown Lane', 261, 'Chetumal International Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Pelecans onocratalus', 'France', 'Mende', '2194 Scoville Terrace', 349, 'Okmulgee Regional Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Cacatua tenuirostris', 'France', 'Fosses', '853 Lakewood Hill', 481, 'Sodankyla Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Conolophus subcristatus', 'France', 'Montpellier', '9 Aberg Hill', 729, 'Carauari Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Lybius torquatus', 'France', 'Perpignan', '7 Toban Street', 789, 'Kunsan Air Base');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Naja haje', 'Greece', 'Ouranoupolis', '219 Ronald Regan Road', 686, 'Ziro Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Kobus defassa', 'Spain', 'Almeria', '833 Mcguire Hill', 765, 'Ouani Airport');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Ceratotherium simum', 'Greece', 'Galátsi', '0252 Fair Oaks Street', 825, 'Fishermans Airfield');
insert into ACCOMMODATIONS (name, country, city, address, price, airport) values ('Anthropoides paradisea', 'France', 'Martigues', '8806 Village Green Circle', 233, 'São Pedro Airport');
